version: '3.3'
services:

  ############
  # postgres #
  ############
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - database-network
      - app-network
    environment:
      - POSTGRES_DB=challenge
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_pass
    volumes:
      - /database-data:/var/lib/postgresql/data/
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: "exit 0"

  # Redis Service
  redis:
    image: redis
    ports:
      - 6379:6379


  ###################
  #   portainer     #
  ###################
  portainer:
    image: portainer/portainer
    container_name: portainer
    stop_grace_period: 1s
    networks:
      - database-network
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  database-network:
    driver : bridge
  app-network:
    driver : bridge

volumes:
  database-data:
  portainer_data: