export enum socketSource {
    GET_ONLINE_USERS = "GET_ONLINE_USERS",
    ONLINE_USERS_LIST = "ONLINE_USERS_LIST",
    CHALLENGE_REQUEST = "CHALLENGE_REQUEST",
    APPROVE_CHALLENGE_REQUEST = "APPROVE_CHALLENGE_REQUEST",
    CANCEL_CHALLENGE_REQUEST = "CANCEL_CHALLENGE_REQUEST",
    NEW_USER_CONNECTION = "NEW_USER_CONNECTION",
    DISCONNECT_USER = "DISCONNECT_USER",
    NEW_CHALLENGE_REQUEST = "NEW_CHALLENGE_REQUEST",
    CHALLENGE_REQUEST_CANCELED = "CHALLENGE_REQUEST_CANCELED",
    CHOOSE_SOME_ANSWER = "CHOOSE_SOME_ANSWER",
    ANSWER_CHOSEN = "ANSWER_CHOSEN",
    START_GAME = "START_GAME",
    SERVER_SOCKET_ERROR = "SERVER_SOCKET_ERROR"
}
